print("hello world")

print("This is the first line of code almost everyone starts with when learning coding")

print("the following are the types of operators in python")

print("1. Arithmetic operators")
print("2. Assignment operators")
print("3. Comparison operators")
print("4. Logical operators")
print("5. Bitwise operators")
print("6. Membership operators")
print("7. Identity operators")
print("Arithmetic operators are used to perform mathematical operations on numbers")
print("1. Addition (+)")
print("2. Subtraction (-)")
print("3. Multiplication (*)")
print("4. Division (/)")
print("5. Modulus (%)")
print("6. Exponentiation (**)")
print("7. Floor division (//)")
print("Assignment operators are used to assign values to variables")
print("1. Assignment (=)")
print("2. Add and assign (+=)")
print("3. Subtract and assign (-=)")
print("4. Multiply and assign (*=)")
print("5. Divide and assign (/=)")
print("6. Modulus and assign (%=)")
print("7. Exponentiation and assign (**=)")
print("8. Floor division and assign (//=)")
print("Comparison operators are used to compare two values and return a boolean value")
print("1. Equal to (==)")
print("2. Not equal to (!=)")
print("3. Greater than (>)")
print("4. Less than (<)")
print("5. Greater than or equal to (>=)")
print("6. Less than or equal to (<=)")
print("Logical operators are used to combine conditional statements")
print("1. and")
print("2. or")
print("3. not")
print("Bitwise operators are used to perform bitwise operations on integers")
print("1. Bitwise AND (&)")
print("2. Bitwise OR (|)")
print("3. Bitwise XOR (^)")
print("4. Bitwise NOT (~)")
print("5. Bitwise left shift (<<)")
print("6. Bitwise right shift (>>)")
print("Membership operators are used to test if a value is in a sequence")
print("1. in")
print("2. not in")
print("Identity operators are used to compare the memory locations of two objects")
print("1. is")
print("2. is not")

print("Type the following number to learn more about the following operators:")
print("1. Arithmetic operators")
print("2. Assignment operators")
print("3. Comparison operators")
print("4. Logical operators")
print("5. Bitwise operators")
print("6. Membership operators")
print("7. Identity operators")

choice = input("Enter your choice: ")
if choice == "1":
    print("Arithmetic operators are used to perform mathematical operations on numbers")
    print("1. Addition (+)")
    print("this operator is used to add two numbers together, for example: 2 + 3 = 5")
    print("input 2 numbers to add together")
    num1 = float(input("Enter the first number: "))
    num2 = float(input("Enter the second number: "))
    result = num1 + num2
    print(f"The sum of {num1} and {num2} is {result}")
    print("addition can also be used to concatenate strings, for example: 'Hello' + ' ' + 'World' = 'Hello World'")
    print("input 2 strings to concatenate together")
    str1 = input("Enter the first string: ")
    str2 = input("Enter the second string: ")
    result_str = str1 + " " + str2
    print(f"The concatenated string is: {result_str}")
    print("addition can also be used to combine lists, for example: [1, 2] + [3, 4] = [1, 2, 3, 4]")
    print("input 2 lists to combine together")
    list1 = input("Enter the first list (separated by commas): ").split(",")
    list2 = input("Enter the second list (separated by commas): ").split(",")
    result_list = list1 + list2
    print(f"The combined list is: {result_list}")
    print("addition can also be used to combine tuples, for example: (1, 2) + (3, 4) = (1, 2, 3, 4)")
    print("input 2 tuples to combine together")
    tuple1 = input("Enter the first tuple (separated by commas): ").split(",")
    tuple2 = input("Enter the second tuple (separated by commas): ").split(",")
    result_tuple = tuple(tuple1) + tuple(tuple2)
    print(f"The combined tuple is: {result_tuple}")
    print("addition cannot be used to combine sets, python uses the | operator or .union(), for example: {1, 2} | {3, 4} = {1, 2, 3, 4}")
    print("input 2 sets to combine together")
    print("using the | operator to combine sets")
    set1 = set(input("Enter the first set (separated by commas): ").split(","))
    set2 = set(input("Enter the second set (separated by commas): ").split(","))
    result_set = set1 | set2
    print(f"The combined set is: {result_set}")
    print("using the .union() method to combine sets")
    set3 = set(input("Enter the third set (separated by commas): ").split(","))
    result_set3 = result_set.union(set3)
    print(f"The combined set is: {result_set3}")
    print("addition can also be used to combine dictionaries, for example: {'a': 1} + {'b': 2} = {'a': 1, 'b': 2}")
    print("input 2 dictionaries to combine together")
    dict1 = {}
    dict2 = {}
    num_items1 = int(input("Enter the number of items in the first dictionary: "))
    for i in range(num_items1):
        key = input("Enter the key: ")
        value = input("Enter the value: ")
        dict1[key] = value
    num_items2 = int(input("Enter the number of items in the second dictionary: "))
    for i in range(num_items2):
        key = input("Enter the key: ")
        value = input("Enter the value: ")
        dict2[key] = value
    result_dict = {**dict1, **dict2}
    print(f"The combined dictionary is: {result_dict}")
    print("addition can also be used to add boolean values, True=1, false=0, for example: True + True = 2")
    print("input 2 boolean values to add together")
    bool1 = input("Enter the first boolean value (True/False): ")
    bool2 = input("Enter the second boolean value (True/False): ")
    bool1_value = 1 if bool1 == "True" else 0
    bool2_value = 1 if bool2 == "True" else 0
    result_bool = bool1_value + bool2_value
    print(f"The sum of {bool1} and {bool2} is {result_bool}")
    print("lets say you check if 3 conditions are met")
    print("is weekend=true, is holiday=true, is raining=true")
    print("if all 3 conditions are true, you can go to the beach")
    print("if any of the conditions are false, you cannot go to the beach")
    print("conditions met= is weekend and is holiday and is raining")
    print("since true has a value of 1, and false has a value of 0, we can use addition to check if all conditions are met")
    print("the total value of the conditions will be 3 if all conditions are true, and less than 3 if any condition is false" )
    print("lets see how that will work in code")
    is_weekend = input("Is it the weekend? (True/False): ")
    is_holiday = input("Is it a holiday? (True/False): ")
    is_raining = input("Is it raining? (True/False): ")
    is_weekend_value = 1 if is_weekend == "True" else 0
    is_holiday_value = 1 if is_holiday == "True" else 0
    is_raining_value = 1 if is_raining == "True" else 0
    total_conditions = is_weekend_value + is_holiday_value + is_raining_value
    if total_conditions == 3:
        print("You can go to the beach!")
    else:
        print("You cannot go to the beach.")
    print("boolean using the .bool() method, for example: bool(1) = True, bool(0) = False")
    print("input a number to check if it is true or false")
    num = int(input("Enter a number: "))
    result_bool_method = bool(num)
    print(f"The boolean value of {num} is {result_bool_method}")
    print("heres how the .bool() method works with the same example of checking if 3 conditions are met")
    is_weekend_bool = bool(input("Is it the weekend? (True/False): "))
    is_holiday_bool = bool(input("Is it a holiday? (True/False): "))
    is_raining_bool = bool(input("Is it raining? (True/False): "))
    total_conditions_bool = is_weekend_bool + is_holiday_bool + is_raining_bool
    if total_conditions_bool == 3:
        print("You can go to the beach!")
    else:
        print("You cannot go to the beach.")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")
    print("5. Modulus (%)")
    print("6. Exponentiation (**)")
    print("7. Floor division (//)")
else:
    print("WIP, please check back later for more information on the other operators")